---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check build process
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

jobs:
  check-qemu-workloads:
    runs-on: ubuntu-20.04
    env:
      DEBUG: true
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies installation
        run: "cd scripts; curl -fsSL http://bit.ly/install_bin | bash"
      - name: Build source code
        run: cd scripts; ./build.sh
